<a href="https://colab.research.google.com/github/shahzeb99/m1/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget https://github.com/xprilion/e2e-ml/raw/master/yelp.csv

--2020-01-14 16:57:30--  https://github.com/xprilion/e2e-ml/raw/master/yelp.csv
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/xprilion/e2e-ml/master/yelp.csv [following]
--2020-01-14 16:57:31--  https://raw.githubusercontent.com/xprilion/e2e-ml/master/yelp.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8091038 (7.7M) [text/plain]
Saving to: ‘yelp.csv.1’

yelp.csv.1          100%[===================>]   7.72M  --.-KB/s    in 0.1s

2020-01-14 16:57:31 (67.5 MB/s) - ‘yelp.csv.1’ saved [8091038/8091038]

In [18]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [10]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords 
from nltk.tokenize import WordPunctTokenizer

In [0]:
df = pd.read_csv("yelp.csv", encoding="ISO-8859-1")

In [5]:
df.head()

              business_id        date  ... useful  funny
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  ...      5      0
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  ...      0      0
2  6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  ...      1      0
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  ...      2      0
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  ...      0      0

[5 rows x 10 columns]

In [6]:
df.describe()

              stars          cool        useful         funny
count  10000.000000  10000.000000  10000.000000  10000.000000
mean       3.777500      0.876800      1.409300      0.701300
std        1.214636      2.067861      2.336647      1.907942
min        1.000000      0.000000      0.000000      0.000000
25%        3.000000      0.000000      0.000000      0.000000
50%        4.000000      0.000000      1.000000      0.000000
75%        5.000000      1.000000      2.000000      1.000000
max        5.000000     77.000000     76.000000     57.000000

import string
import re

def clean_text(text):
    text = text.translate(string.punctuation)
    
    text = text.lower().split()
    
    stops = set(stopwords.words("english"))
    text = [w for w in text if not w in stops and len(w) >= 3]
    text = " ".join(text)
    
    text = re.sub(r"[^a-z0-9^,!.\/'+-=]", " ", text) 
    
    return text

In [0]:
yelp_data = df[['business_id', 'user_id', 'stars', 'text']]

In [19]:
yelp_data['text'] = yelp_data['text'].apply(clean_text)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [0]:
X_train, y_train, X_test, y_test = train_test_split(yelp_data['text'], df['business_id'], test_size = 0.2)

In [0]:
user_df = yelp_data[['user_id','text']]
business_df = yelp_data[['business_id', 'text']]

In [0]:
user_df = user_df.groupby('user_id').agg({'text': ' '.join})
business_df = business_df.groupby('business_id').agg({'text': ' '.join})

In [0]:
user_vectorizer = TfidfVectorizer(tokenizer = WordPunctTokenizer().tokenize, max_features=1000)

In [0]:
business_vectorizer = TfidfVectorizer(tokenizer = WordPunctTokenizer().tokenize, max_features=1000)

In [0]:
user_vectors = user_vectorizer.fit_transform(user_df['text'])

In [0]:
business_vectors = business_vectorizer.fit_transform(business_df['text'])

In [0]:
userRatings = pd.pivot_table(yelp_data, values='stars', index=['user_id'], columns=['business_id'])

In [28]:
userRatings.head()

business_id             -0QBrNvhrPQCaeo7mTo0zQ  ...  zyYRWnimLbQt9aCCI_2MZw
user_id                                         ...
--65q1FpAL_UQtVZ2PTGew                     NaN  ...                     NaN
--VxRvXk3b8FwsSbC2Zpxw                     NaN  ...                     NaN
--rlgfAvvi0BtfRDA1p-VQ                     NaN  ...                     NaN
-2S6keboidRPly-h5lBfkA                     NaN  ...                     NaN
-2XA34d6OGYEUuzqC7yhBg                     NaN  ...                     NaN

[5 rows x 4174 columns]

In [0]:
P = pd.DataFrame(user_vectors.toarray(), index=user_df.index, columns=user_vectorizer.get_feature_names())
Q = pd.DataFrame(business_vectors.toarray(), index=business_df.index, columns=business_vectorizer.get_feature_names())

In [0]:
def matrix_factorization(R, P, Q, steps=1, gamma=0.001,lamda=0.02):
    for step in range(steps):
        for i in R.index:
            for j in R.columns:
                if R.loc[i,j]>0:
                    eij=R.loc[i,j]-np.dot(P.loc[i],Q.loc[j])
                    P.loc[i]=P.loc[i]+gamma*(eij*Q.loc[j]-lamda*P.loc[i])
                    Q.loc[j]=Q.loc[j]+gamma*(eij*P.loc[i]-lamda*Q.loc[j])
        e=0
        for i in R.index:
            for j in R.columns:
                if R.loc[i,j]>0:
                    e= e + pow(R.loc[i,j]-np.dot(P.loc[i],Q.loc[j]),2)+lamda*(pow(np.linalg.norm(P.loc[i]),2)+pow(np.linalg.norm(Q.loc[j]),2))
        if e<0.001:
            break
        
    return P,Q

In [32]:
%%time
P, Q = matrix_factorization(userRatings, P, Q, steps=1, gamma=0.001,lamda=0.02)

CPU times: user 7min 31s, sys: 90.1 ms, total: 7min 31s
Wall time: 7min 31s

In [0]:
import pickle
output = open('model.pkl', 'wb')
pickle.dump(P, output)
pickle.dump(Q, output)
pickle.dump(user_vectorizer, output)